config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about_us' => 'static_pages#about'
  devise_for :users
  resources :users, only: [:index, :show]
  resources :activities, only: [:new, :create, :index, :show, :edit, :update, :destroy]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, allow_blank: false
  validates :date, presence: true, allow_blank: false
  validates :duration, presence: true, allow_blank: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity_params, only: %i[show edit update destroy]

  def index
    @activities = current_user.activities.all.order(created_at: :desc)
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = current_user.activities.new(activity_params)
    if @activity.save
      flash[:success] = 'Your activity was successfully added!'
      redirect_to @activity
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find_by(id: params[:id])
    if @activity.update(activity_params)
      flash[:success] = 'Post successfully edited'
      redirect_to activities_path
    else
      render :edit
    end
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def destroy
    @activity = Activity.find(params[:id])
    return unless current_user.id == @activity.user_id

    @activity.destroy
    flash[:success] = 'Activity deleted successfully!'
    redirect_back(fallback_location: root_path)
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :date, :duration)
  end

  def set_activity_params
    @activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # Whitelist the following form fields so that we can process them, if coming from
  # a Devise sign up form.
  before_action :configure_premitted_parameters, if: :devise_controller?
  
  protected

  def configure_premitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation) }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end
  
  # GET to /users/:id
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity do |f| %>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.select :name, ['Running', 'Walking', 'Cycling', 'Swimming', 'Elliptical', 'Strength Training', 'Circuit Training', 'Core Strength', 'Arc Training', 'Rowing', 'Hiking', 'Mountain Biking', 'Skating', 'Nordic Walking', 'XC Skiing', 'Downhill Skiing', 'Snow Boarding', 'Wheelchair'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :duration %>
    <%= f.number_field :duration, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit Activity", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="offset-md-3 col-md-6">
      <h1 class="text-center">Edit Your Activity</h1>
        <div class="card bg-light">
          <div class="card-body">
            <%= render 'form' %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">All Activities Participated In</h1>
        <div class="card bg-light">
          <div class="card-body">
            <table class="table table-striped">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Date</th>
                  <th scope="col">Activity Name</th>
                  <th scope="col">Duration(mins)</th>
                  <th scope="col">Edit</th>
                  <th scope="col">Delete</th>
                </tr>
              </thead>

              <tbody>
                <% @activities.each do |activity| %>
                  <tr>
                    <td><%= link_to activity.date.strftime("%d-%m-%Y"), activity %></td>
                    <td><%= link_to activity.name, activity %></td>
                    <td><%= link_to activity.duration, activity %></td>
                    <td>
                      <% if activity.user == current_user %>
                        <%= link_to '<i class="fa fa-pencil-square-o go-center"></i>'.html_safe, edit_activity_path(activity) %>
                      <% end %>
                    </td>
                    <td>
                      <% if activity.user == current_user %>
                        <%= link_to ('<i class="fa fa-trash go-center"></i>').html_safe, activity, :method=> :delete, data: { confirm: 'Are you sure?' } %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="offset-md-3 col-md-6">
      <h1 class="text-center">Create Your Activity</h1>
        <div class="card bg-light">
          <div class="card-body">
            <%= render 'form', activity: @activity %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <h1 class="text-center">Activity Description</h1>
        <div class="card bg-light mt-3">
          <div class="card-body text-center mt-3">
            <p><strong>Date:</strong> <%= @activity.date.strftime("%d-%m-%Y") %></p>
            <p><strong>Name:</strong> <%= @activity.name %></p>
            <p><strong>Duration:</strong> <%= @activity.duration %>mins</p>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="container-fluid flash-container mt-3">
  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{type}" %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto">
  <div class="container-fluid">
    <ul class="bd-footer-links mt-2">
      <li><%= link_to "Copyriight 2020. All rights reseved. Move and Groove.", root_path, class: "nav-link  text-muted mr-3" %></li>
      <li class="screen-size"><%= link_to "Home", root_path, class: "nav-link color-change" %></li>
      <li class="screen-size"><%= link_to "About Us", about_us_path, class: "nav-link color-change mr-2" %></li>
      <% if user_signed_in? %>
        <li class="screen-size"><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary navbar-btn" %></li>
      <% else %>
        <li class="screen-size"><%= link_to "Register", new_user_registration_path, class: "btn btn-outline-secondary mr-2" %></li>
        <li class="screen-size"><%= link_to "Log In", new_user_session_path, class: "btn btn-outline-secondary" %></li>
      <% end %>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light diff-color">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-cogs"></i> Move and Groove
      <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto mr-2">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link"  %></li>
          <li class="nav-item"><%= link_to "About Us", about_us_path, class: "nav-link"  %></li>
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Create Activity", new_activity_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "My Activities", activities_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "My Account", edit_user_registration_path, class: "nav-link" %></li>
          <% end %>
        </ul>
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary navbar-btn log-out" %>
          <% else %>
            <%= link_to "Register", new_user_registration_path, class: "btn btn-outline-secondary mr-2 log-out" %>&nbsp;
            <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-secondary log-out" %>
          <% end %>
        </div>
      </div>
    </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Move and Groove</title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container-fluid">
  <div class="row mt-5">
    <div class="offset-md-1 col-md-10">
      <div class="jumbotron">
        <h1 class="display-4">About Us</h1>
        <p class="lead">Move and Groove is a fitness application that allows users to sign up and log activities of different kinds. The app displays activity data from the user, based on various metrics such as steps taken or calories burned. For example: Distance walked with exercise intensity divided by distance run during 10 minutes in time (based off average walking speed).</p>

        <p class="lead">The apps tracks your progress using Google Fit's Activity Profiles. There are four levels which include Fitness, Speed, Goal Setting & Motivation categories; if you don't find one right for something you'll be able to select another set via quick search feature.</p>

        <% if user_signed_in? %>
          <%= link_to "Create Activity", new_activity_path, class: "btn btn-success btn-lg mt-4" %>
        <% else %>
          <%= link_to "Create Account", new_user_registration_path, class: "btn btn-success btn-lg mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid">
  <div class="row mt-3">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
      <div class="jumbotron">
        <h1 class="display-5">Keep fit and healthy</h1>
        <p class="lead mt-3">Move and Groove is a fitness application that allows users to sign up and log activities of different kinds. The app displays activity data from the user, based on various metrics such as steps taken or calories burned. For example: Distance walked with exercise intensity divided by distance run during 10 minutes in time (based off average walking speed).</p>

        <p class="lead">The apps tracks your progress using Google Fit's Activity Profiles. There are four levels which include Fitness, Speed, Goal Setting & Motivation categories; if you don't find one right for something you'll be able to select another set via quick search feature.</p>

        <% if user_signed_in? %>
          <%= link_to "Create Activity", new_activity_path, class: "btn btn-success btn-lg mt-4" %>
        <% else %>
          <%= link_to "Create Account", new_user_registration_path, class: "btn btn-success btn-lg mt-3" %>
        <% end %>
      </div>
    </div>

    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
          <div class="card" style="width: 100%">
            <i class="fas fa-running"></i>
            <h5 class="text-center">Running</h5>
          </div>
        </div>

        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 space-me">
          <div class="card" style="width: 100%">
            <i class="fas fa-walking"></i>
            <h5 class="text-center">Walking</h5>
          </div>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
          <div class="card" style="width: 100%">
            <i class="fas fa-biking"></i>
            <h5 class="text-center">Cycling</h5>
          </div>
        </div>

        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 space-me">
          <div class="card" style="width: 100%">
            <i class="fas fa-swimmer"></i>
            <h5 class="text-center">Swimming</h5>
          </div>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
          <div class="card" style="width: 100%">
            <i class="fas fa-skating"></i>
            <h5 class="text-center">Skating</h5>
          </div>
        </div>

        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 mb-4 space-me">
          <div class="card" style="width: 100%">
            <i class="fas fa-dumbbell"></i>
            <h5 class="text-center">Strength Training</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <h1 class="text-center">All Users</h1>
        <ul class="list-unstyled">
          <% @users.each do |user| %>
          <li class="mb-2">
              <div class="card bg-light mt-3">
                <div class="card-body">
                  <%= link_to user do %>
                    <h5><%= user.email %></h5>
                  <% end %>
                </div>
              </div>
          </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <h1 class="text-center">User Profile</h1>
        <div class="card bg-light mt-4">
          <div class="card-body text-center">
            <h5><%= @user.email %></h5>
          </div>
        </div>
    </div>
  </div>
</div>